spring:
  datasource:
    driver_class_name: oracle.jdbc.OracleDriver
    password: None00010001
    url: jdbc:oracle:thin:@reacttodocrj8s_tp?TNS_ADMIN=C:/Users/r1agu/Downloads/wallet/wallet
    username: TODOUSER
  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    user:
      name: ${ui_username}
      password: ${ui_password}